language: python

jobs:
  include:
    - name: "Python 3.6.0 on AMD64 Linux"
      python: 3.6
      os: linux
      arch: amd64
    - name: "Python 3.7.0 on AMD64 Linux"
      python: 3.7 
      os: linux
      arch: amd64
    - name: "Python 3.8.0 on AMD64 Linux"
      python: 3.8 
      os: linux
      arch: amd64
    - name: "Python 3.9.0 on AMD64 Linux"
      python: 3.9  
      os: linux
      arch: amd64
    - name: "Python 3.6.0 on ARM64 Linux"
      python: 3.6
      os: linux
      arch: arm64
    - name: "Python 3.7.0 on ARM64 Linux"
      python: 3.7 
      os: linux
      arch: arm64
    - name: "Python 3.8.0 on ARM64 Linux"
      python: 3.8 
      os: linux
      arch: arm64
    - name: "Python 3.9.0 on ARM64 Linux"
      python: 3.9    
      os: linux
      arch: arm64       
    - name: "Python on macOS"
      os: osx
      osx_image: xcode12 
      language: shell       
    - name: "Python 3.6.0 on Windows"
      os: windows           
      language: shell       
      before_install:
        - choco install python --version 3.6.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH
    - name: "Python 3.7.0 on Windows"
      os: windows           
      language: shell       
      before_install:
        - choco install python --version 3.7.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python37:/c/Python37/Scripts:$PATH
    - name: "Python 3.8.0 on Windows"
      os: windows           
      language: shell       
      before_install:
        - choco install python --version 3.8.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python38:/c/Python38/Scripts:$PATH
    - name: "Python 3.9.0 on Windows"
      os: windows           
      language: shell       
      before_install:
        - choco install python --version 3.9.0
        - python -m pip install --upgrade pip
      env: PATH=/c/Python39:/c/Python39/Scripts:$PATH

install:
  - pip3 install dbr opencv-python

branches:
  only:
    - main

script:
    - python3 ./test.py ./images/1D-1-OverExposure.jpg || python my_app.py ./test.py ./images/1D-1-OverExposure.jpg